"""Add Twin tables migration"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20240616_01_add_twins"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust as needed ###
    op.create_table(
        "organization_twin",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
    )
    op.create_table(
        "role_twin",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organization_twin.id"), nullable=True),
    )
    op.create_table(
        "person_twin",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("knowledge_id", sa.Integer(), sa.ForeignKey("knowledge_twin.id"), nullable=True),
    )
    op.create_table(
        "knowledge_twin",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
    )
    op.create_table(
        "agent_twin",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True, server_default="idle"),
        sa.Column("person_id", sa.Integer(), sa.ForeignKey("person_twin.id"), nullable=True),
    )
    # association table person_role
    op.create_table(
        "person_role",
        sa.Column("person_id", sa.Integer(), sa.ForeignKey("person_twin.id"), primary_key=True, nullable=False),
        sa.Column("role_id", sa.Integer(), sa.ForeignKey("role_twin.id"), primary_key=True, nullable=False),
    )
    # Knowledge node and relationship
    op.create_table(
        "knowledge_node",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("knowledge_id", sa.Integer(), sa.ForeignKey("knowledge_twin.id"), nullable=True),
    )
    op.create_table(
        "knowledge_relationship",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("source_id", sa.Integer(), sa.ForeignKey("knowledge_node.id"), nullable=False),
        sa.Column("target_id", sa.Integer(), sa.ForeignKey("knowledge_node.id"), nullable=False),
        sa.Column("relation_type", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("knowledge_relationship")
    op.drop_table("knowledge_node")
    op.drop_table("person_role")
    op.drop_table("agent_twin")
    op.drop_table("knowledge_twin")
    op.drop_table("person_twin")
    op.drop_table("role_twin")
    op.drop_table("organization_twin")
